version: '{build}'
os: Visual Studio 2017 RC
cache: C:\Users\appveyor\.dnx\packages
build_script:
- ps: >-
    dotnet restore

    dotnet build src\Kraken\Kraken.csproj --configuration Release

    $rnp = Resolve-Path(".\RELEASENOTES.md")

    $rnc = [IO.File]::ReadAllText($rnp)

    Set-AppveyorBuildVariable -Name release_notes -Value $rnctest_script:
- ps: >-
    cd test\Kraken.Tests

    dotnet test

    cd ..\..\
before_deploy:
- ps: >-
    npm install -g bower

    npm install -g gulp

    dotnet publish src\Kraken\Kraken.csproj --configuration Release

    nuget pack Kraken.nuspec -NoPackageAnalysis

    Get-ChildItem .\Kraken.*.nupkg | % { Push-AppveyorArtifact $_.FullName -DeploymentName GitHub }
deploy:
- provider: GitHub
  description: $(release_notes)
  auth_token:
    secure: ttUANtrgmx3KYQ8JqCQ1t2FnA8vCEFH9WBlmdGmxoBjSb6o55ZnSoqaKWf2HZLMV
  artifact: GitHub
  draft: false
  prerelease: true
  on:
    appveyor_repo_tag: true